### ISSUE TITLE
Georeferencing Error: Records found outside KY > .5 mile

### ISSUE THREAD

**Issue by dbloom** [uam-vertnet/uam-fish#13]
Hello UAM,

The Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 2 records in the VertNet data portal that should plot withing the bounds of the state of Kentucky, but actually plot outside the state by half a mile or more.

If you'd like to discuss these issues with the folks at KFWIS, contact me and I will connect you with them.

institutioncode	collectioncode	catalognumber	locality	decimallatitude	decimallongitude	geodeticdatum	coordinateuncertaintyinmeters
AUM	Fish	11922	Trammel Creek, 0.4 airmi NNW of Petroleum, Hwy 31 E	36.528136	-85.696783	not recorded (forced WGS84)	 
AUM	Fish	29530	Bayou du Chein, 5.4 mi SE Clinton at Davis Rd	30.3873	-88.7736	not recorded (forced WGS84)	 

(There may not be data contained within each Darwin Core field for each of these records.)

**Comment by jandreslopez** [comment]
Hi David,

Looks like those are AUM specimens not UAM.

A

________________________________________
Curator of Fishes
University of Alaska Museum
P.O. Box 756960
907 Yukon Drive
Fairbanks, AK 99775
ph:  907 474 7828
fax: 907 474 1987
e-mail: jalopez2@alaska.edu skype: j_andres_lopez

Assistant Professor
School of Fisheries and Ocean Sciences
Fisheries Division
207A O'Neill Building
Fairbanks, AK 99775-7220
________________________________________

**Comment by dbloom** [comment]
Ack!  35 issues later...

Thanks for noting this.  I will close this issue and move the appropriate repository.

Thanks for the heads up.
